pipeline:

  build_and_publish_develop:
    image: plugins/docker
    repo: ${DRONE_REPO,,}
    secrets: [ docker_username, docker_password ]
    force_tag: true
    tags: latest
    when:
      branch: develop
      event: push

  redeploy_develop:
    image: docker:18.06.0-ce
    environment:
      - DOCKER_HOST=tcp://192.168.100.184:2375
      - DOCKER_USERNAME=${docker_username}
      - DOCKER_PASSWORD=${docker_password}
    secrets: [ docker_username, docker_password ]
    commands:
      - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker service update --image ${DRONE_REPO,,}:latest ugm-dev_web --with-registry-auth
    when:
      status: success
      event: push
      branch: develop

  build_master:
    image: node:10.15
    commands:
      - rm -rf /cache/*
      - npm ci
      - npm run build
      - cp -r dist/* /cache/
    volumes:
      - cache:/cache
    when:
      branch: master
      event: push

  publish_master:
    image: plugins/s3
    environment:
      - PLUGIN_SOURCE=/cache/**/*
      - PLUGIN_TARGET=/
      - PLUGIN_STRIP_PREFIX=/cache
      - PLUGIN_REGION=eu-north-1
      - PLUGIN_ACL=public-read
      - PLUGIN_BUCKET=www.urbangirlsmovement.org
      - PLUGIN_ACCESS_KEY=${aws_access_key}
      - PLUGIN_SECRET_KEY=${aws_secret_key}
    secrets: [ aws_access_key, aws_secret_key ]
    volumes:
      - cache:/cache
    when:
      status: success
      event: push
      branch: master

volumes:
  - name: cache
    temp: {}
